name: Android Lint&Test&Build CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  android-ci:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        ref: ${{ github.event.pull_request.head.sha }}
    - name: set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
      
    - name: lint with Gradle
      run: ./gradlew lintRelease
      
    - name: Testing with Gradle
      run: ./gradlew testDebugUnitTest

    - name: Build with Gradle
      run: ./gradlew build

    - name: Run Danger
      if: success() || failure() # Do nothing if canceled
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        JOB_STATUS: ${{ job.status }}
      run: |
        bundle exec danger \
          --dangerfile=.github/workflows/Dangerfile \
          --remove-previous-comments \
          --fail-on-errors=true
