name: Dummy for test

on:
  workflow_dispatch:

jobs:
  build:
    name: Build on merge # ビルド

    runs-on: ubuntu-latest

    steps:
      - name: Check out
        uses: actions/checkout@v4
      - name: set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle
      - name: Build with Gradle
        run: ./gradlew assembleDebug
      - name: Upload apk file
        uses: actions/upload-artifact@v3
        with:
          name: apk
          path: app/build/outputs/apk/debug/app-debug.apk

  release:
    name: Generate Release Note
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Download apk file
        uses: actions/download-artifact@v3
        with:
          name: apk
          path: app-debug.apk
      #      - name: Generate Release Note
      #        uses: actions/github-script@v6
      #        id: release-note
      #        with: # 試作
      #          script: |
      #            const {id} = await github.rest.repos.createRelease({
      #              owner: context.repo.owner,
      #              repo: context.repo.repo,
      #              tag_name: 'v1.0.0',
      #              generate_release_notes: true,
      #            });
      #            return id;
      - name: upload asset
        uses: actions/github-script@v6
        id: upload-asset
        with:
          script: |
            const fs = require('fs');
            const latest = await github.rest.repos.getLatestRelease({
              owner: context.repo.owner,
              repo: context.repo.repo,
            });
            const data = fs.readFileSync("./app-debug.apk");
            await github.rest.repos.uploadReleaseAsset({
              owner: context.repo.owner,
              repo: context.repo.repo,
              release_id: latest.id,
              name: latest.tag_name,
              data: data,
            });

