name: "setup"
on:
  # TODO 動作確認用・外部公開時に削除予定
  workflow_dispatch:
  push:
    branches:
      - main

env:
  # TODO テンプレートリポジトリを外部公開したら変更
  src_repo: yumemi/droid-training-renewal

jobs:
  setup:
    runs-on: ubuntu-20.04
    permissions:
      contents: write
      issues: write
    timeout-minutes: 10
    if: github.event.repository.name != env.src_repo
    env:
      src_repo: ${{ env.src_repo }}
      # TODO テンプレートリポジトリを外部公開したらtokenは不要
      src_repo_token: ${{ secrets.SRC_REPO_TOKEN }}
      dst_repo: ${{ github.repository }}
      dst_repo_token: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Check out
        uses: actions/checkout@v3
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '2.7'
      - name: Copy Issues
        run: |
          gem install octokit -v '6.0.1'
          ruby .github/workflows/copy-issue.rb
      - name: Cleanup
        run: | 
          mv -f .github/README_TEMPLATE.md README.md 
          rm -rf .github/workflows
      - name: Commit
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git commit -m "Template Setup"
      - name: Push
        uses: ad-m/github-push-action@v0.6.0
        with:
          branch: main
          github_token: ${{ secrets.GITHUB_TOKEN }}
